openapi: 3.0.1
info:
  title: Entity Search Service
  description: This is an abstraction for entity search service exposed on Elastic
    Search platform
  version: 1.0.0

tags:
  - name: search
    description: This is entity search searvice
paths:
  /search/{entity}:
    post:
      tags:
        - search
      summary: Search entity using elastic search service
      description: Search entity using search service
      operationId: searchEnity
      parameters:
        - name: entity
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: search Criteria will contain all filters and other criteria to search entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Criteria'
        required: true
      responses:
        "400":
          description: Bad request
          content: { application/json: {
                            schema: {
                              "$ref": '#/components/schemas/Error'
                            }
                       }
                   }
        "404":
          description: Entity not found
          content: { application/json: {
            schema: {
              "$ref": '#/components/schemas/Error'
            }
          }
          }
        "409":
          description: Validation error
          content: { application/json: {
            schema: {
              "$ref": '#/components/schemas/Error'
            }
          }
          }
          "500":
            description: Internal server error
            content: { application/json: {
              schema: {
                "$ref": '#/components/schemas/Error'
              }
            }
            }
      x-codegen-request-body-name: searchCriteria
components:
  schemas:
    Criteria:
      required:
        - filters
        - offset
        - orders
        - size
      type: object
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/Filter'
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        size:
          type: integer
          minimum: 1
          maximum: 50
        offset:
          type: integer
          minimum: 0
    Order:
      required:
        - asc
        - field
      type: object
      properties:
        field:
          type: string
          nullable: false
        asc:
          type: boolean
    Filter:
      required:
        - field
        - operator
        - value
      type: object
      properties:
        field:
          type: string
          nullable: false
        operator:
          type: string
          enum:
            - eq
            - ne
            - any
            - gt
            - gte
            - lt
            - lte
            - between
            - not_between
        value:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
x-original-swagger-version: "2.0"
