apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-search
  labels:
    app: entity-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app : entity-search
  template:
    metadata:
      labels:
        app: entity-search
    spec:
      containers:
        - name: user-service-app
          image: db-cache-layer/entity-search:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9001

---

kind: Service
apiVersion: v1
metadata:
  name:  entity-search-svc
spec:
  selector:
    app:  entity-search
  ports:
    - port:  80
      targetPort:  9001