server:
  port: ${sp:9001}
log:
  file:
    path: ./logs
spring:
  application:
    name: ENTITY-SEARCH-SERVICE
  profiles:
    active: @spring.profiles.active@
---
spring:
  config:
    activate:
      on-profile: demo
    logging:
      level:
        org:
          springframework:
            data:
              elasticsearch:
                core: DEBUG
name: demo-yaml
environment: demo
enabled: false
elastic-search:
    baseUrl:  ${ELASTIC_BASE_URL:192.168.80.41:9200}
    username: ${ELASTIC_USER_ID:elastic}
    pwd: ${ELASTIC_PASSWORD:-r_05kc5qqWqNHZcDWlj}
    keystore:
      file:
        path: ${KEYSTORE_PATH:${user.home}/keystore.jks}
      pwd: ${JKS_PASSWORD:elasticsearch}

---
spring:
  config:
    activate:
      on-profile: stage
name: stage-yaml
environment: stage
enabled: false
elastic-search:
  baseUrl:  ${ELASTIC_BASE_URL:192.168.80.41:9200}
  username: ${ELASTIC_USER_ID:elastic}
  pwd: ${ELASTIC_PASSWORD:-r_05kc5qqWqNHZcDWlj}
  keystore:
    file:
      path: ${KEYSTORE_PATH:${user.home}/keystore.jks}
    pwd: ${JKS_PASSWORD:elasticsearch}
---
spring:
  config:
    activate:
      on-profile: test
name: test-yaml
environment: test
enabled: false
elastic-search:
  baseUrl:  ${ELASTIC_BASE_URL:localhost:9200}
  username: ${ELASTIC_USER_ID:elastic}
  pwd: ${ELASTIC_PASSWORD:elastic}
  keystore:
    file:
      path: ${KEYSTORE_PATH:${user.home}/keystore.jks}
    pwd: ${JKS_PASSWORD:elasticsearch}